name: 'Full Deploy Firebase'
author: 'Fork of Sho Mizutani <lowply@github.com> by Elmarti'
description: 'A GitHub Action to deploy all Firebase assets. Fork of "Deploy to Firebase"'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'red'